# -*- coding: utf-8 -*-
"""python basics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16D7WTmbzKK7M77p3yiyszPgMg7I3AO1b
"""

foods = ("Paneer", "Dosa", "Idly", "Icecream", "Kitkat") #create a list
print(foods[0]) #printing first item
print(foods[-1]) #printing the last item using -1
print(len(foods)) #printing length of the list

foods = ["Paneer", "Dosa", "Idly", "Icecream", "Kitkat"] #create a list
foods.append("Samosa")#adding samosa to the end of the list #append adds at the end of the list
print(foods)
foods.remove("Kitkat")#removing kitkat from the list
print(foods)
foods.insert(2, "Biryani")#adding biryani at position 2
print(foods)
foods.pop(2)#removing the item at index 2
print(foods)

foods = ["Paneer", "Dosa", "Idly", "Icecream", "Samosa"]

# direct loop gives value directly
for food in foods: #food is something created on spot and we can call it anything. it takes the value of each item in the list one by one
    print(food)

# Style 2 - using index (gives us the index)
for i in range(len(foods)):
    print(foods[i])
for i in range(len(foods)):
    print(i, foods[i]) #prints the index and the food

foods = ["Paneer", "Dosa", "Idly", "Icecream", "Samosa"]
#if/else loop
for food in foods:
    if food == "Dosa":
        print("This is my favourite!")
    else:
        print("This is okay")

# create a dictionary with 3 friends and their ages
friends = {
    "Anand": 22, #anand,rahul,priya are the keys
    "Rahul": 23, #22,23,21 are the values
    "Priya": 21
}
#for name in friends, Python automatically knows that name will take each key one by one because that's how dictionary loops work.
# print one person's age
print(friends["Anand"])

# loop through and print everyone's name and age
for name in friends:
    print(name, friends[name]) #name refers to the key which is 22,23,21

numbers = [1, 2, 3, 1, 2, 5, 3]
print(numbers)
#entire set and printing unique values
unique = set(numbers)
print(unique)

"""list stores values in order and allows duplicates.It has an index. list is like a ordered shelf.


set stores unique values only and does not allow duplicates.It does not have an index. set is a bag of unique items. instant lookup

dictionary stores key value pairs for keys no duplicates and for values yes it allows duplicates.It doesnot have an index
dictionary is basically a phonebook. instant lookup


"""

